/* I Ching judgments — direct English (Zhou Yi) translation, judgment text only.
   Keyed by King Wen number (1-64). Source: iching-english-only.md (user translation). */
window.ICHING_JUDGMENTS = {
 "1": {"name":"Heaven","pinyin":"Qián","trig":"Heaven over Heaven","judgment":"Great offering. Beneficial to divine."},
 "2": {"name":"Earth","pinyin":"Kūn","trig":"Earth over Earth","judgment":"Great offering. Beneficial to divine concerning a mare. The nobleman has somewhere to go: first he loses his way, later he finds a lord. Beneficial. In the southwest, gain friends; in the northeast, lose them. A settled divination: auspicious."},
 "3": {"name":"Sprouting","pinyin":"Zhūn","trig":"Water over Thunder","judgment":"Great offering. Beneficial to divine. Do not set out anywhere. Beneficial to install a prince."},
 "4": {"name":"Ignorance","pinyin":"Méng","trig":"Mountain over Water","judgment":"Offering. It is not I who seek the ignorant young; the ignorant young seek me. The first divination informs them; a second and third muddy it, and what is muddied is not told. Beneficial to divine."},
 "5": {"name":"Waiting","pinyin":"Xū","trig":"Water over Heaven","judgment":"There are captives. A radiant offering. The divination is auspicious. Beneficial to cross the great river."},
 "6": {"name":"Dispute","pinyin":"Sòng","trig":"Heaven over Water","judgment":"There are captives; then obstruction. Be wary: midway, auspicious; in the end, ominous. Beneficial to see the great man. Not beneficial to cross the great river."},
 "7": {"name":"The Army","pinyin":"Shī","trig":"Earth over Water","judgment":"Divine. A seasoned elder: auspicious. No blame."},
 "8": {"name":"Alliance","pinyin":"Bǐ","trig":"Water over Earth","judgment":"Auspicious. Take the origin-oracle: a great and lasting divination. No blame. The unquiet come to join; the latecomer, ominous."},
 "9": {"name":"Small Restraint","pinyin":"Xiǎo xù","trig":"Wind over Heaven","judgment":"Offering. Dense clouds, no rain, out of my own western marches."},
 "10": {"name":"Treading","pinyin":"Lǚ","trig":"Heaven over Lake","judgment":"Treading on the tiger's tail: it does not bite the man. Offering."},
 "11": {"name":"Peace","pinyin":"Tài","trig":"Earth over Heaven","judgment":"The small goes, the great comes. Auspicious. Offering."},
 "12": {"name":"Obstruction","pinyin":"Pǐ","trig":"Heaven over Earth","judgment":"Obstruction by the wrong people. Not beneficial for the nobleman to divine. The great goes, the small comes."},
 "13": {"name":"Fellowship","pinyin":"Tóng rén","trig":"Heaven over Fire","judgment":"Gathering men in the open country. Offering. Beneficial to cross the great river. Beneficial for the nobleman to divine."},
 "14": {"name":"Great Possession","pinyin":"Dà yǒu","trig":"Fire over Heaven","judgment":"Great offering."},
 "15": {"name":"Modesty","pinyin":"Qiān","trig":"Earth over Mountain","judgment":"Offering. The nobleman has an end."},
 "16": {"name":"Ease","pinyin":"Yù","trig":"Thunder over Earth","judgment":"Beneficial to install princes and to march the army."},
 "17": {"name":"Following","pinyin":"Suí","trig":"Lake over Thunder","judgment":"Great offering. Beneficial to divine. No blame."},
 "18": {"name":"Decay","pinyin":"Gǔ","trig":"Mountain over Wind","judgment":"Great offering. Beneficial to cross the great river. Three days before the jia-day, three days after the jia-day."},
 "19": {"name":"Approach","pinyin":"Lín","trig":"Earth over Lake","judgment":"Great offering. Beneficial to divine. Come the eighth month, there is misfortune."},
 "20": {"name":"Viewing","pinyin":"Guān","trig":"Wind over Earth","judgment":"The hands washed, the offering not yet brought. There are captives, gazing up in awe."},
 "21": {"name":"Biting Through","pinyin":"Shì hé","trig":"Fire over Thunder","judgment":"Offering. Beneficial to apply legal judgment."},
 "22": {"name":"Adornment","pinyin":"Bì","trig":"Mountain over Fire","judgment":"Offering. A small benefit in having somewhere to go."},
 "23": {"name":"Stripping Away","pinyin":"Bō","trig":"Mountain over Earth","judgment":"Not beneficial to have somewhere to go."},
 "24": {"name":"Return","pinyin":"Fù","trig":"Earth over Thunder","judgment":"Offering. Going out and coming in without ill; friends come, no blame. Back and forth on its course — in seven days it returns. Beneficial to have somewhere to go."},
 "25": {"name":"Without Falsehood","pinyin":"Wú wàng","trig":"Heaven over Thunder","judgment":"Great offering. Beneficial to divine. If one is not upright, there are troubles; not beneficial to have somewhere to go."},
 "26": {"name":"Great Restraint","pinyin":"Dà xù","trig":"Mountain over Heaven","judgment":"Beneficial to divine. Not to eat at home: auspicious. Beneficial to cross the great river."},
 "27": {"name":"The Jaws","pinyin":"Yí","trig":"Mountain over Thunder","judgment":"The divination: auspicious. Observe the jaws; one seeks the filling of one's own mouth."},
 "28": {"name":"Great Exceeding","pinyin":"Dà guò","trig":"Lake over Wind","judgment":"The ridgepole sags. Beneficial to have somewhere to go. Offering."},
 "29": {"name":"The Pit","pinyin":"Kǎn","trig":"Water over Water","judgment":"The doubled pit. There are captives. It is the heart that offers. To go brings esteem."},
 "30": {"name":"Radiance","pinyin":"Lí","trig":"Fire over Fire","judgment":"Beneficial to divine. Offering. To rear a cow: auspicious."},
 "31": {"name":"Stirring","pinyin":"Xián","trig":"Lake over Mountain","judgment":"Offering. Beneficial to divine. To take a wife: auspicious."},
 "32": {"name":"Constancy","pinyin":"Héng","trig":"Thunder over Wind","judgment":"Offering. No blame. Beneficial to divine. Beneficial to have somewhere to go."},
 "33": {"name":"Retreat","pinyin":"Dùn","trig":"Heaven over Mountain","judgment":"Offering. A small benefit in divining."},
 "34": {"name":"Great Strength","pinyin":"Dà zhuàng","trig":"Thunder over Heaven","judgment":"Beneficial to divine."},
 "35": {"name":"Advance","pinyin":"Jìn","trig":"Fire over Earth","judgment":"The Lord of Kang is given horses in abundance, and in a single day granted audience three times."},
 "36": {"name":"Brightness Wounded","pinyin":"Míng yí","trig":"Earth over Fire","judgment":"Beneficial in a hard divination."},
 "37": {"name":"The Household","pinyin":"Jiā rén","trig":"Wind over Fire","judgment":"Beneficial for a woman to divine."},
 "38": {"name":"Opposition","pinyin":"Kuí","trig":"Fire over Lake","judgment":"In small matters, auspicious."},
 "39": {"name":"Halting","pinyin":"Jiǎn","trig":"Water over Mountain","judgment":"Beneficial in the southwest, not beneficial in the northeast. Beneficial to see the great man. The divination: auspicious."},
 "40": {"name":"Release","pinyin":"Xiè","trig":"Thunder over Water","judgment":"Beneficial in the southwest. If there is nowhere to go, then to return is auspicious. If there is somewhere to go, then early is auspicious."},
 "41": {"name":"Decrease","pinyin":"Sǔn","trig":"Mountain over Lake","judgment":"There are captives. Supremely auspicious. No blame. One may divine. Beneficial to have somewhere to go. What need of much? Two bowls of grain will serve for the offering."},
 "42": {"name":"Increase","pinyin":"Yì","trig":"Wind over Thunder","judgment":"Beneficial to have somewhere to go. Beneficial to cross the great river."},
 "43": {"name":"Resolution","pinyin":"Guài","trig":"Lake over Heaven","judgment":"Proclaimed in the king's court: captives, an outcry, danger. Announce it from your own town. Not beneficial to take up arms at once. Beneficial to have somewhere to go."},
 "44": {"name":"Encounter","pinyin":"Gòu","trig":"Heaven over Wind","judgment":"The woman is bold. Do not take her to wife."},
 "45": {"name":"Gathering","pinyin":"Cuì","trig":"Lake over Earth","judgment":"Offering. The king comes to the ancestral temple. Beneficial to see the great man. Offering. Beneficial to divine. Use a great sacrificial beast: auspicious. Beneficial to have somewhere to go."},
 "46": {"name":"Ascending","pinyin":"Shēng","trig":"Earth over Wind","judgment":"Great offering. Use it to see the great man. Do not fret. To campaign southward: auspicious."},
 "47": {"name":"Confinement","pinyin":"Kùn","trig":"Lake over Water","judgment":"Offering. Divine. For the great man, auspicious. No blame. There are words, but they are not believed."},
 "48": {"name":"The Well","pinyin":"Jǐng","trig":"Water over Wind","judgment":"The town may be moved, but not the well. Nothing lost, nothing gained. Comers and goers draw from the well. But if one almost reaches the water, yet the rope falls short of the well, and the jug is broken — ominous."},
 "49": {"name":"Change","pinyin":"Gé","trig":"Lake over Fire","judgment":"On the ji-day, then captives. Great offering. Beneficial to divine. Regret vanishes."},
 "50": {"name":"The Cauldron","pinyin":"Dǐng","trig":"Fire over Wind","judgment":"Supremely auspicious. Offering."},
 "51": {"name":"Thunder","pinyin":"Zhèn","trig":"Thunder over Thunder","judgment":"Offering. Thunder comes — terror, terror! Then laughter and talk, ha-ha. Thunder startles for a hundred li, yet he does not drop the sacrificial ladle and the libation-wine."},
 "52": {"name":"Stilling","pinyin":"Gèn","trig":"Mountain over Mountain","judgment":"Keeping the back still, he no longer feels his body; walking in his courtyard, he does not see the people there. No blame."},
 "53": {"name":"Gradual Advance","pinyin":"Jiàn","trig":"Wind over Mountain","judgment":"A maiden marrying: auspicious. Beneficial to divine."},
 "54": {"name":"The Marrying Maiden","pinyin":"Guī mèi","trig":"Thunder over Lake","judgment":"To march out: ominous. Nothing to gain."},
 "55": {"name":"Abundance","pinyin":"Fēng","trig":"Thunder over Fire","judgment":"Offering. The king attains it. Do not grieve; be like the sun at noon."},
 "56": {"name":"The Wanderer","pinyin":"Lǚ","trig":"Fire over Mountain","judgment":"A small offering. The traveller's divination: auspicious."},
 "57": {"name":"Compliance","pinyin":"Xùn","trig":"Wind over Wind","judgment":"A small offering. Beneficial to have somewhere to go. Beneficial to see the great man."},
 "58": {"name":"Joy","pinyin":"Duì","trig":"Lake over Lake","judgment":"Offering. Beneficial to divine."},
 "59": {"name":"Dispersion","pinyin":"Huàn","trig":"Wind over Water","judgment":"Offering. The king comes to the ancestral temple. Beneficial to cross the great river. Beneficial to divine."},
 "60": {"name":"Limitation","pinyin":"Jié","trig":"Water over Lake","judgment":"Offering. Bitter restraint cannot be persisted in."},
 "61": {"name":"Inmost Captives","pinyin":"Zhōng fú","trig":"Wind over Lake","judgment":"Pigs and fish: auspicious. Beneficial to cross the great river. Beneficial to divine."},
 "62": {"name":"Small Exceeding","pinyin":"Xiǎo guò","trig":"Thunder over Mountain","judgment":"Offering. Beneficial to divine. Fit for small matters, not for great ones. The flying bird leaves its cry: not fitting to go up, but fitting to go down. Greatly auspicious."},
 "63": {"name":"Already Across","pinyin":"Jì jì","trig":"Water over Fire","judgment":"A small offering. Beneficial to divine. At first auspicious; in the end, disorder."},
 "64": {"name":"Not Yet Across","pinyin":"Wèi jì","trig":"Fire over Water","judgment":"Offering. The little fox, almost across, wets its tail. Nothing to gain."}
};
